server {
 listen 443;
 server_name _;

 root /var/www/devops-site;
 index index.html;

 ssl_certificate /etc/nginx/ssl/certs/devops-site.com.crt;
 ssl_certificate_key /etc/nginx/ssl/certs/devops-site.com.key;

 ssl_session_timeout 1d;
 ssl_session_cache 10m;

 access_log /var/log/nginx/devops-site-ssl.access.log
 error_log /var/log/nginx/devops-site-ssl.error.log

 autoindex on;

 location /heath.html{
	 access_log off;
 }
}

