server {
 listen 80;
 server_name _;

 root /var/www/devops-site;
 index index.html;

 access_log /var/log/nginx/devops-site.access.log;
 error_log /var/log/nginx/devops-site.error.log;

 location /{
 return 301 https://$host$request_uri;
 }

 location /health {
 access_log off;
 }
}

